owner: schnow265
repo: uptime

sites:
  # Search Engines
  - name: Kagi
    url: https://www.kagi.com
  - name: DuckDuckGo
    url: https://www.duckduckgo.com
  - name: Google
    url: https://www.google.com
  - name: Bing
    url: https://www.bing.com
  
  # "Random" websites.
  - name: Wikipedia
    url: https://www.wikipedia.org

  - name: Internet Archive
    url: https://www.archive.org

  - name: Software Heritage Archive
    url: https://archive.softwareheritage.org

  - name: Talilscale API
    url: https://api.tailscale.com/api
    expectedStatusCodes:
      - 200
      - 201
      - 404

  # ironic.
  - name: GitHub
    url: https://github.com

  # Cloudflare.
  - name: Cloudflare
    url: https://www.cloudflare.com
  - name: Cloudflare Status
    url: https://www.cloudflarestatus.com

  # DNS Servers
  - name: Google DNS
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53
    icon: https://google.com/favicon.ico
  
  - name: Cloudflare DNS
    check: "tcp-ping"
    url: 1.1.1.1
    port: 53
    icon: https://cloudflare.com/favicon.ico
  
  - name: Quad9 DNS
    check: "tcp-ping"
    url: 9.9.9.9
    port: 53
    icon: https://quad9.net/favicon.svg

  # AI bs
  - name: Mistal API
    url: https://api.mistral.ai/
    expectedStatusCodes:
      - 200
      - 201
      - 404
    icon: https://mistral.ai/favicon.ico

  - name: OpenAI API
    url: https://api.openai.com
    expectedStatusCodes:
      - 200
      - 201
      - 421
    icon: https://platform.openai.com/docs/static/favicon-platform.svg

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/$OWNER/$REPO/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO