owner: schnow265
repo: uptime

sites:
  # Search Engines
  - name: DuckDuckGo
    url: https://www.duckduckgo.com
    
  - name: Kagi
    url: https://www.kagi.com
  
  # "Random" websites.
  - name: Wikipedia
    url: https://www.wikipedia.org

  - name: Internet Archive
    url: https://www.archive.org

  - name: Software Heritage Archive
    url: https://archive.softwareheritage.org

  - name: Talilscale API
    url: https://api.tailscale.com/api
    expectedStatusCodes:
      - 200
      - 201
      - 404

  # Cloudflare.
  - name: Cloudflare
    url: https://www.cloudflare.com
  - name: Cloudflare Status
    url: https://www.cloudflarestatus.com

  # DNS Servers
  - name: Google DNS
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53
    icon: https://google.com/favicon.ico
  
  - name: Cloudflare DNS
    check: "tcp-ping"
    url: 1.1.1.1
    port: 53
    icon: https://cloudflare.com/favicon.ico
  
  - name: Quad9 DNS
    check: "tcp-ping"
    url: 9.9.9.9
    port: 53
    icon: https://quad9.net/favicon.svg

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/$OWNER/$REPO/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
